// ---------------------------------------------------------------
// Copyright (c) Paul.Ward@ccoder.co.uk
// ---------------------------------------------------------------

using System.Text;

using cCoder.Packer.Models.Reports;

namespace cCoder.Packer.Services.Processings.Reports;

internal sealed partial class AssetReportGraphProcessingService
    : IAssetReportGraphProcessingService
{
    private readonly IReadOnlyList<AssetReportAsset> assets;

    private readonly IReadOnlyList<AssetReportAsset> layouts;

    private readonly IReadOnlyList<AssetReportAsset> pages;

    private readonly IReadOnlyList<AssetReportAsset> components;

    private readonly IReadOnlyList<AssetReportAsset> scripts;

    private readonly IReadOnlyList<AssetReportAsset> resources;

    private readonly Dictionary<string, List<AssetReportAsset>> componentsByName;

    private readonly Dictionary<string, List<AssetReportAsset>> scriptsByName;

    private readonly HashSet<string> componentNames;

    private readonly HashSet<string> reachableComponents =
        new(comparer: StringComparer.OrdinalIgnoreCase);

    private readonly HashSet<string> reachableScripts =
        new(comparer: StringComparer.OrdinalIgnoreCase);

    private readonly HashSet<string> reachableResourceKeys =
        new(comparer: StringComparer.OrdinalIgnoreCase);

    private readonly HashSet<string> shadowedComponents =
        new(comparer: StringComparer.OrdinalIgnoreCase);

    private readonly HashSet<string> unresolvedComponents =
        new(comparer: StringComparer.OrdinalIgnoreCase);

    private readonly HashSet<string> unresolvedScripts =
        new(comparer: StringComparer.OrdinalIgnoreCase);

    public AssetReportGraphProcessingService(IReadOnlyList<AssetReportAsset> assets)
    {
        this.assets = assets;

        this.layouts = OfType(type: "Layouts");

        this.pages = OfType(type: "Pages");

        this.components = OfType(type: "Components");

        this.scripts = OfType(type: "Scripts");

        this.resources = OfType(type: "Resources");

        this.componentsByName = IndexByName(values: this.components);

        this.scriptsByName = IndexByName(values: this.scripts);

        this.componentNames = new HashSet<string>(
            collection: this.componentsByName.Keys,
            comparer: StringComparer.OrdinalIgnoreCase);
    }

    public string Build() =>
        TryCatch(operation: () => BuildAssetReportGraph());

    private string BuildAssetReportGraph()
    {
        StringBuilder report = new();

        report.AppendLine(value: "# cCoder asset usage report");

        report.AppendLine();

        report.AppendLine(
            value: "> Generated by `packer -report` from every JSON " +
                "business object below the configured Data directory.");

        report.AppendLine();

        report.AppendLine(
            value: $"Generated: {DateTimeOffset.UtcNow:O}");

        report.AppendLine();

        foreach (AssetReportAsset layout in this.layouts.OrderBy(
            keySelector: NameOf,
            comparer: StringComparer.OrdinalIgnoreCase))
        {
            AppendLayout(report: report, layout: layout);
        }

        AppendReviewQueues(report: report);

        return report.ToString();
    }

    private void AppendLayout(StringBuilder report, AssetReportAsset layout)
    {
        string layoutName = NameOf(asset: layout);

        AssetReportAsset[] layoutPages = [.. this.pages
            .Where(predicate: page => string.Equals(
                a: AssetReportProcessingService.GetString(value: page.Value, name: "Layout"),
                b: layoutName,
                comparisonType: StringComparison.OrdinalIgnoreCase))
            .OrderBy(
                keySelector: page =>
                    AssetReportProcessingService.GetString(value: page.Value, name: "Path"),
                comparer: StringComparer.OrdinalIgnoreCase)];

        HashSet<string> expanded = new(
            comparer: StringComparer.OrdinalIgnoreCase);

        report.AppendLine(value: $"## Layout: {layoutName}");

        report.AppendLine();

        report.AppendLine(value: $"- Source: `{layout.RelativePath}`");

        report.AppendLine(value: $"- Pages: {layoutPages.Length}");

        report.AppendLine();

        AppendReferences(
            report: report,
            asset: layout,
            indent: string.Empty,
            expanded: expanded);

        report.AppendLine(value: "### Pages");

        report.AppendLine();

        foreach (AssetReportAsset page in layoutPages)
        {
            string resourceKey =
                AssetReportProcessingService.GetString(value: page.Value, name: "ResourceKey")
                ?? string.Empty;

            if (!string.IsNullOrWhiteSpace(value: resourceKey))
            {
                this.reachableResourceKeys.Add(item: resourceKey);
            }

            report.AppendLine(
                value: $"- [ ] Page " +
                    $"`/{AssetReportProcessingService.GetString(value: page.Value, name: "Path")}` — " +
                    $"resource key: `{resourceKey}`; " +
                    $"source: `{page.RelativePath}`");

            AppendReferences(
                report: report,
                asset: page,
                indent: "  ",
                expanded: expanded);
        }

        report.AppendLine();
    }

    private void AppendReferences(
        StringBuilder report,
        AssetReportAsset asset,
        string indent,
        ISet<string> expanded)
    {
        AssetReportReferences references = AssetReportProcessingService.GetReferences(
            value: asset.Value,
            componentNames: this.componentNames);

        foreach (string resource in references.Resources)
        {
            report.AppendLine(
                value: $"{indent}- [ ] Resource token `{resource}`");
        }

        foreach (string script in references.Scripts)
        {
            AppendScript(
                report: report,
                requester: asset,
                name: script,
                indent: indent,
                expanded: expanded);
        }

        foreach (string component in references.Components)
        {
            AppendComponent(
                report: report,
                requester: asset,
                name: component,
                indent: indent,
                expanded: expanded);
        }
    }

    private void AppendComponent(
        StringBuilder report,
        AssetReportAsset requester,
        string name,
        string indent,
        ISet<string> expanded)
    {
        AssetReportAsset? component = Resolve(
            index: this.componentsByName,
            requester: requester,
            name: name,
            shadowed: this.shadowedComponents);

        if (component is null)
        {
            this.unresolvedComponents.Add(item: name);

            report.AppendLine(
                value: $"{indent}- [ ] Component `{name}` — unresolved");

            return;
        }

        this.reachableComponents.Add(item: component.RelativePath);

        string resourceKey =
            AssetReportProcessingService.GetString(value: component.Value, name: "ResourceKey")
            ?? string.Empty;

        if (!string.IsNullOrWhiteSpace(value: resourceKey))
        {
            this.reachableResourceKeys.Add(item: resourceKey);
        }

        report.AppendLine(
            value: $"{indent}- [ ] Component `{NameOf(asset: component)}` " +
                $"— {(component.IsCommonCache ? "Common Cache" : "Application")}; " +
                $"resource key: `{resourceKey}`");

        if (!expanded.Add(item: component.RelativePath))
        {
            report.AppendLine(
                value: $"{indent}  - Already expanded above");

            return;
        }

        AppendReferences(
            report: report,
            asset: component,
            indent: indent + "  ",
            expanded: expanded);
    }

    private void AppendScript(
        StringBuilder report,
        AssetReportAsset requester,
        string name,
        string indent,
        ISet<string> expanded)
    {
        AssetReportAsset? script = Resolve(
            index: this.scriptsByName,
            requester: requester,
            name: name);

        if (script is null)
        {
            this.unresolvedScripts.Add(item: name);

            report.AppendLine(
                value: $"{indent}- [ ] Script `{name}` — unresolved");

            return;
        }

        this.reachableScripts.Add(item: script.RelativePath);

        report.AppendLine(value:
            $"{indent}- [ ] Script `{NameOf(asset: script)}`");

        if (expanded.Add(item: script.RelativePath))
        {
            AppendReferences(
                report: report,
                asset: script,
                indent: indent + "  ",
                expanded: expanded);
        }
    }

    private void AppendReviewQueues(StringBuilder report)
    {
        AssetReportAsset[] unreachableComponents = [.. this.components
            .Where(predicate: component =>
                !this.reachableComponents.Contains(
                    item: component.RelativePath)
                && !this.shadowedComponents.Contains(
                    item: component.RelativePath))];

        AssetReportAsset[] unreachableScripts = [.. this.scripts
            .Where(predicate: script =>
                !this.reachableScripts.Contains(
                    item: script.RelativePath))];

        string[] resourceKeys = [.. this.resources
            .Select(selector: ResourceKeyOf)
            .Where(predicate: value =>
                !string.IsNullOrWhiteSpace(value: value))
            .Distinct(comparer: StringComparer.OrdinalIgnoreCase)];

        report.AppendLine(value: "## Review queues");

        report.AppendLine();

        AppendQueue(
            report: report,
            title: "Shadowed component duplicates",
            values: this.shadowedComponents);

        AppendQueue(
            report: report,
            title: "Unresolved component references",
            values: this.unresolvedComponents);

        AppendQueue(
            report: report,
            title: "Unresolved script references",
            values: this.unresolvedScripts);

        AppendQueue(
            report: report,
            title: "Unreachable components",
            values: unreachableComponents.Select(
                selector: component => component.RelativePath));

        AppendQueue(
            report: report,
            title: "Unreachable resource keys",
            values: resourceKeys.Where(predicate: key =>
                !this.reachableResourceKeys.Contains(item: key)));

        AppendQueue(
            report: report,
            title: "Unreachable scripts",
            values: unreachableScripts.Select(
                selector: script => script.RelativePath));

        report.AppendLine(value: "## Totals");

        report.AppendLine();

        report.AppendLine(value: $"- Directories scanned: " +
            $"{DirectoryRoots().Count}");

        report.AppendLine(value: $"- Layouts: {this.layouts.Count}");

        report.AppendLine(value: $"- Pages: {this.pages.Count}");

        report.AppendLine(value: $"- Reachable components: " +
            $"{this.reachableComponents.Count} / {this.components.Count}");

        report.AppendLine(value: $"- Reachable scripts: " +
            $"{this.reachableScripts.Count} / {this.scripts.Count}");

        int reachableResourceKeyCount = resourceKeys.Count(
            predicate: key =>
                this.reachableResourceKeys.Contains(item: key));

        report.AppendLine(value: $"- Reachable resource keys: " +
            $"{reachableResourceKeyCount} / {resourceKeys.Length}");
    }

    private static void AppendQueue(
        StringBuilder report,
        string title,
        IEnumerable<string> values)
    {
        report.AppendLine(value: $"### {title}");

        report.AppendLine();

        string[] items = [.. values
            .Distinct(comparer: StringComparer.OrdinalIgnoreCase)
            .Order(comparer: StringComparer.OrdinalIgnoreCase)];

        if (items.Length == 0)
        {
            report.AppendLine(value: "- [ ] None");
        }
        else
        {
            foreach (string item in items)
            {
                report.AppendLine(value: $"- [ ] `{item}`");
            }
        }

        report.AppendLine();
    }

    private static AssetReportAsset? Resolve(
        Dictionary<string, List<AssetReportAsset>> index,
        AssetReportAsset requester,
        string name,
        HashSet<string>? shadowed = null)
    {
        if (!index.TryGetValue(key: name, value: out List<AssetReportAsset>? values))
        {
            return null;
        }

        AssetReportAsset[] scopedValues =
        [
            .. values.Where(predicate: value => string.Equals(
                a: value.Source,
                b: requester.Source,
                comparisonType: StringComparison.OrdinalIgnoreCase)),
        ];

        if (scopedValues.Length == 0 && !requester.IsCommonCache)
        {
            scopedValues =
            [
                .. values.Where(predicate: value => value.IsCommonCache),
            ];
        }

        if (scopedValues.Length == 0)
        {
            return null;
        }

        AssetReportAsset resolved = scopedValues[0];

        if (shadowed is not null)
        {
            foreach (AssetReportAsset value in scopedValues.Where(
                predicate: value => value != resolved))
            {
                shadowed.Add(item: value.RelativePath);
            }
        }

        return resolved;
    }

    private IReadOnlyList<AssetReportAsset> OfType(string type) =>
        [.. this.assets
            .Where(predicate: asset => string.Equals(
                a: asset.Type,
                b: type,
                comparisonType: StringComparison.OrdinalIgnoreCase))];

    private static Dictionary<string, List<AssetReportAsset>> IndexByName(
        IEnumerable<AssetReportAsset> values) =>
        values
            .GroupBy(
                keySelector: NameOf,
                comparer: StringComparer.OrdinalIgnoreCase)
            .ToDictionary(
                keySelector: group => group.Key,
                elementSelector: group => group.ToList(),
                comparer: StringComparer.OrdinalIgnoreCase);

    private static string NameOf(AssetReportAsset asset) =>
        AssetReportProcessingService.GetString(value: asset.Value, name: "Name")
        ?? Path.GetFileNameWithoutExtension(path: asset.RelativePath);

    private static string ResourceKeyOf(AssetReportAsset asset)
    {
        string[] segments = asset.RelativePath.Split(separator: '/');

        return segments.Length > 2 ? segments[^3] : string.Empty;
    }

    private IReadOnlyCollection<string> DirectoryRoots() =>
        [.. this.assets
            .Select(selector: asset =>
                asset.RelativePath.Split(separator: '/')[0])
            .Distinct(comparer: StringComparer.OrdinalIgnoreCase)];
}